### PR TITLE
SENSE2 improvements

### PR DESCRIPTION
**Pull request by michaelschar**
Hi Nick,

We made some what we think are improvements to SENSE2 and other nodes in bni-nodes. The main difference is that a widget "oversampling ratio" was added, and that the matrices were increased accordingly. At least for the SheppLogan phantom those changes improved image quality significantly.
I attached 2 images after 50 iterations, left without increasing the matrix size and the original oversampling ratio of 1.5. And on the right with an oversampling ratio of 1.375 and the now automatically increased matrix size.

Mike
left-oversampling1p5-originalmtx-right-oversampling1p375andincreasedmtx

### CODE REVIEW

**Comment by nckz** [comment]
This is awesome!  Thanks Mike and Gabriel.  I've tested this with my spiral project and it looks good.

I've got a couple of questions:
1. Should we crop to the 'mtx_original' size for the output (i.e. remove the extra zeropadding produced by the oversample ratio)?  In my applications I'm expecting the selected reconstruction matrix -is there a reason to keep the larger matrix?
2. I'm having an issue with the "step" Button on the SENS2 node.  Its failing with:

```
Thu Mar 10 13:49:46 2016 - gpi.node:601 - ERROR - Sense2: compute() failed.
Start SENSE
Thu Mar 10 13:50:13 2016 - gpi.functor:369 - ERROR - PROCESS: 'Sense2':'' compute() failed.
Traceback (most recent call last):
  File "/Users/nick/src/framework-github/lib/gpi/functor.py", line 367, in run
    self._proxy.append(['retcode', self._func()])
  File "/Users/nick/gpi/bni/sense/GPI/Sense2_GPI.py", line 149, in compute
    x_iterations[:-1,:,:] = self.getData('x iterations')
ValueError: could not broadcast input array from shape (5,95,95) into shape (5,1,95,95)
```

Are you guys having this issue?

Nick

**Comment by michaelschar** [comment]
Thanks Nick!

I'm working on some more changes and will make sure those 2 items are included when I commit those.

Mike

**Comment by michaelschar** [comment]
In this version I replaced your elegant loop2 structure and made it clunky again restricting the data to two extra dimensions (for instance slices and dynamics), whereas the first extra dimension can have the same or different coordinates to allow golden-angle dynamic imaging. 
The reason to move to the clunky setup is that the c implementation of FFTW is much faster in looping over those extra dimensions compared to looping in python and only sending each 2D slice to FFTW. For my 40 cardiac phases data with a large matrix size the reconstruction decreased from 1.4 hrs to 5.4 minutes. (my previous CG SENSE node needed 17 minutes). 
Currently, SENSE2, Grid2Kaiser, and DeGrid2Kaiser have identical functions in them. I will move them into a python utils library next.

**Comment by nckz** [comment]
I kind of like having the dimensions of length 1 as a placeholder for dynamics and slices.  I might add a "Squeeze" node to simplify the array if when we're not using those dimensions/loops.

I guess thats not too surprising that fftw loops faster. I just figured that the number of iterations was relatively low and that it wouldn't make such a difference.  -nice work!

**Comment by nckz** [comment]
I'm still having a problem with the "step" button.  If I 'step' to 5 iterations I get this:

stepto5

If I loop to 5 iterations I get the correct solution:

loopto5

In looking at the 'x iterations' outputs for each:
stepto5_tile
iterto5_tile

**Comment by michaelschar** [comment]
I used the cropped csm in the outport for the "step" button iterations. I added the oversampled csm as an additional outport.

**Comment by nckz** [comment]
Thanks guys, this looks good.

**Pull request merged**
